name: Release
on:
  push:
    branches:
      - dev
    
permissions:
  contents: read 

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # To be able to publish a GitHub release
      issues: write # To be able to comment on released issues
      pull-requests: write # To be able to comment on released pull requests
    outputs:
      release-tag: ${{ steps.release.outputs.tag }}

    env:
      CHANGELOG_FILE: ${{ github.workspace }}/packages/ui/CHANGELOG.md  
      TITLE: '[UI] Automatic Release'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 // required by semantic release
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run semantic-release -C packages/ui
          echo "tag=${TAG_NAME}" >> "${GITHUB_OUTPUT}"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ env.TITLE }}
          commit-message: 'chore(manyui): release ${{ steps.release.outputs.tag }}'
          author: 'github-actions <41898282+github-actions[bot]@users.noreply.github.com>'
          labels: automation
          branch: ui-release
          base: dev
          body: |
            Latest release: ${{ steps.release.outputs.tag }} and changelog update
      - name: Enable Pull Request auto merge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ steps.cpr.outputs.pull-request-number }}
        shell: bash
        run:
          gh pr merge -R ${{ github.repository }} --merge --auto ${{ env.pr_number }} -b "" -t '⇄ PR-#${{ env.pr_number }} | ${{ env.TITLE }}'